"""
Border Surveillance Anomaly Detection - FastAPI Backend
=========================================================

This is the main entry point for the backend API. It exposes endpoints
for:
- Uploading an image/frame for anomaly detection
- Retrieving detection history (alert logs)
- Health check (used by deployment platforms like Render)

Run locally with:
    uvicorn app.main:app --reload --port 8000

API docs (auto-generated by FastAPI) will be available at:
    http://localhost:8000/docs
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.routes import detection
from app.utils.database import init_db

app = FastAPI(
    title="Border Surveillance Anomaly Detection API",
    description="Detects intrusion-style anomalies (people/vehicles in restricted zones) from uploaded surveillance images using YOLOv8.",
    version="1.0.0",
)

# CORS: allows the React frontend (running on a different domain/port)
# to call this API. In production, replace "*" with your actual frontend
# URL for better security.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the SQLite database (creates tables if they don't exist)
init_db()

# Register API routes
app.include_router(detection.router, prefix="/api", tags=["detection"])


@app.get("/")
def root():
    return {"message": "Border Surveillance Anomaly Detection API is running."}


@app.get("/health")
def health_check():
    """Used by Render/uptime checks to confirm the service is alive."""
    return {"status": "ok"}
